### ISSUE TITLE
Rename this repo. openwhisk-client-python

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk-client-python#1]
By convention all OpenWhisk clients, by agreement, will use the same naming convention/prefix.

**Comment by dubee** [comment]
@mrutkows, actually this repo isn't needed as the Python CLI is backed up in the openwhisk repo.

**Comment by rabbah** [comment]
@dubeejw in the long run we will use this repo (to create the python client for example) and remove the duplicate from the main repo. (Should we remove it now?)

There are some users who still use the python CLI on occasion - myself included because of missing functionality (e.g., log stripping) or to verify behavior (e.g., schema encoding headaches). Not having the backup as handy might accelerate fixing these in the main line CLI.

**Comment by mrutkows** [comment]
@dubeejw @csantanapr we have been discussing taking the CLIs out of core openwhisk and keeping them in separate project repos. as the correct organization.  We already have an issue trying to extend the CLI and would rather have the API frameworks as separable entities.

**Comment by csantanapr** [comment]
>remove the duplicate from the main repo. (Should we remove it now?)

Let's remove, and the suffering will make the go CLI pickup what you are missing.

What we do with wskadmin?, maybe we can have a script to git clone the python client into core. then wskadmin can reference to it.

**Comment by rabbah** [comment]
leave `wskadmin` alone, it's self contained (did that long ago).

**Comment by csantanapr** [comment]
>leave wskadmin alone, it's self contained (did that long ago).

👍  I forgot it was self contained

**Comment by mrutkows** [comment]
"What we do with wskadmin?, maybe we can have a script to git clone the python client into core. then wskadmin can reference to it." @csantanapr  

So this is viable (and same for Go?)?

**Comment by cclauss** [comment]
Related to https://github.com/openwhisk/openwhisk/issues/1902

**Comment by rabbah** [comment]
renamed.
